create table if not exists wa_sessions (
  id bigint generated by default as identity primary key,
  msisdn text not null,
  step text not null default 'welcome',
  name text,
  target_program text,
  signature_experience text,
  key_strength text,
  goals text,
  word_limit int,
  draft_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists wa_sessions_msisdn_idx on wa_sessions(msisdn);

create table if not exists wa_messages (
  id bigint generated by default as identity primary key,
  msisdn text not null,
  direction text not null check (direction in ('in','out')),
  message_text text,
  meta jsonb,
  created_at timestamptz default now()
);

create index if not exists wa_messages_msisdn_idx on wa_messages(msisdn);
